-- AlterTable
ALTER TABLE `UserSettings` ADD COLUMN `focusMode` BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE `UserSettings` ADD COLUMN `focusStart` INTEGER NOT NULL DEFAULT 2;
ALTER TABLE `UserSettings` ADD COLUMN `focusEnd` INTEGER NOT NULL DEFAULT 10;
ALTER TABLE `UserSettings` ADD COLUMN `focusRevealMs` INTEGER NOT NULL DEFAULT 1000;
